import { createTheme, ThemeProvider, CssBaseline, Container, Typography, List, ListItem, ListItemText, Link, Box } from '@mui/material';

const darkTheme = createTheme({
    palette: {

        background: {
            default: 'linear-gradient(to bottom, #121212, #1e1e1e)',
            paper: '#1e1e1e',
        },
        text: {
            primary: '#ffffff',
            secondary: '#b0b0b0',
        },
    },
});

const PrivacyPolicy = () => {
    return (
      <Box sx={{ background: "#1b2c50", color: "#c9d1d9", minHeight: "100vh" }}>
        <ThemeProvider theme={darkTheme}>
          <CssBaseline />
          <Container     sx={{
          paddingTop: "80px",
          paddingBottom: "80px",

          color: "#fff",}}>
            <Typography variant="h4" align="center" gutterBottom>
              Privacy Policy
            </Typography>
            <Typography paragraph>
              This Privacy Policy describes Our policies and procedures on the
              collection, use, and disclosure of Your information when You use
              the Service and tells You about Your privacy rights and how the
              law protects You.
            </Typography>
            <Typography paragraph>
              We use Your Personal data to provide and improve the Service. By
              using the Service, You agree to the collection and use of
              information in accordance with this Privacy Policy. This Privacy
              Policy has been created with the help of the Privacy Policy
              Generator.
            </Typography>

            <Typography variant="h5" gutterBottom>
              Interpretation and Definitions
            </Typography>
            <Typography variant="h6" gutterBottom>
              Interpretation
            </Typography>
            <Typography paragraph>
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </Typography>

            <Typography variant="h6" gutterBottom>
              Definitions
            </Typography>
            <Typography paragraph>
              For the purposes of this Privacy Policy:
            </Typography>
            <List>
              <ListItem>
                <ListItemText
                  primary="Account"
                  secondary="A unique account created for You to access our Service or parts of our Service."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Company"
                  secondary="(referred to as either 'the Company', 'We', 'Us' or 'Our' in this Agreement) refers to AKILAM TECHNOLOGY LLP, D25, 10th Cross West Extn. Thillai Nagar Trichy, TN 620018."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Cookies"
                  secondary="Small files placed on Your device by a website, containing details of Your browsing history among its many uses."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Country"
                  secondary="Tamil Nadu, India."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Device"
                  secondary="Any device that can access the Service such as a computer, a cellphone, or a digital tablet."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Personal Data"
                  secondary="Any information that relates to an identified or identifiable individual."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Service"
                  secondary="Refers to the Website."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Service Provider"
                  secondary="Any natural or legal person who processes the data on behalf of the Company."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Usage Data"
                  secondary="Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself."
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="Website"
                  secondary={
                    <Link
                      href="https://akilamtechnology.com"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      https://akilamtechnology.com
                    </Link>
                  }
                />
              </ListItem>
              <ListItem>
                <ListItemText
                  primary="You"
                  secondary="The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service."
                />
              </ListItem>
            </List>

            <Typography variant="h5" gutterBottom>
              Collecting and Using Your Personal Data
            </Typography>
            <Typography variant="h6" gutterBottom>
              Types of Data Collected
            </Typography>
            <Typography variant="subtitle1" gutterBottom>
              Personal Data
            </Typography>
            <Typography paragraph>
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information that can be used to contact or
              identify You. Personally identifiable information may include, but
              is not limited to:
            </Typography>
            <List>
              <ListItem>
                <ListItemText primary="Email address" />
              </ListItem>
              <ListItem>
                <ListItemText primary="First name and last name" />
              </ListItem>
              <ListItem>
                <ListItemText primary="Phone number" />
              </ListItem>
              <ListItem>
                <ListItemText primary="Address, State, Province, ZIP/Postal code, City" />
              </ListItem>
              <ListItem>
                <ListItemText primary="Usage Data" />
              </ListItem>
            </List>

            <Typography variant="subtitle1" gutterBottom>
              Usage Data
            </Typography>
            <Typography paragraph>
              Usage Data is collected automatically when using the Service.
              Usage Data may include information such as Your Device&apos;s
              Internet Protocol address (e.g. IP address), browser type, browser
              version, the pages of our Service that You visit, the time and
              date of Your visit, the time spent on those pages, unique device
              identifiers, and other diagnostic data.
            </Typography>

            <Typography variant="h6" gutterBottom>
              Tracking Technologies and Cookies
            </Typography>
            <Typography paragraph>
              We use Cookies and similar tracking technologies to track the
              activity on Our Service and store certain information. Tracking
              technologies used are beacons, tags, and scripts to collect and
              track information and to improve and analyze Our Service.
            </Typography>

            <Typography variant="h5" gutterBottom>
              Use of Your Personal Data
            </Typography>
            <Typography paragraph>
              The Company may use Personal Data for the following purposes:
            </Typography>
            <List>
              <ListItem>
                <ListItemText primary="To provide and maintain our Service, including to monitor the usage of our Service." />
              </ListItem>
              <ListItem>
                <ListItemText primary="To manage Your Account: to manage Your registration as a user of the Service." />
              </ListItem>
              <ListItem>
                <ListItemText primary="To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of communication." />
              </ListItem>
              <ListItem>
                <ListItemText primary="To manage Your requests: To attend and manage Your requests to Us." />
              </ListItem>
            </List>

            <Typography variant="h5" gutterBottom>
              Security of Your Personal Data
            </Typography>
            <Typography paragraph>
              The security of Your Personal Data is important to Us, but
              remember that no method of transmission over the Internet, or
              method of electronic storage is 100% secure. While We strive to
              use commercially acceptable means to protect Your Personal Data,
              We cannot guarantee its absolute security.
            </Typography>

            <Typography variant="h5" gutterBottom>
              Children&apos;s Privacy
            </Typography>
            <Typography paragraph>
              Our Service does not address anyone under the age of 13. We do not
              knowingly collect personally identifiable information from anyone
              under the age of 13. If You are a parent or guardian and You are
              aware that Your child has provided Us with Personal Data, please
              contact Us.
            </Typography>

            <Typography variant="h5" gutterBottom>
              Changes to this Privacy Policy
            </Typography>
            <Typography paragraph>
              We may update Our Privacy Policy from time to time. We will notify
              You of any changes by posting the new Privacy Policy on this page.
            </Typography>
          </Container>
        </ThemeProvider>
      </Box>
    );
};

export default PrivacyPolicy;
